#!/bin/bash
set -x
customer=$1 
ver=$2
netelement_type=$3
envstate=$4


if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] || [ -z "$4" ]; then
  echo 'one or more variables are undefined'        
  echo " usage ./scriptname customer version NE_TYPE Environment ( Prod / Preprod )"
 exit 1
fi

for csv_stripped in `ls -lrt /srv/customers/hotstorage/configs/$ver/$customer/$netelement_type/*.csv | awk '{print $9}' | cut -d'/' -f8 | cut -d'-' -f1`
	do 
	if [ -f /srv/customers/hotstorage/configs/$ver/$customer/$netelement_type/$csv_stripped.conf ] 
	then 
		echo "File already exists"
	else
	/srv/customers/hotstorage/configs/newcustomer/mklstconf $csv_stripped $customer $netelement_type $ver $envstate >> /srv/customers/hotstorage/configs/$ver/$customer/$netelement_type/$csv_stripped.conf1
	cat /srv/customers/hotstorage/configs/$ver/$customer/$netelement_type/$csv_stripped.conf1 | sed 's/\[\"\,\"float\"\]//g' | sed 's/mutate {convert => }//g' | sed 's/site\","float/site\","string/g'| sed 's/date\","float/date\","string/g' | sed 's/_name\","float/_name\","string/g' | sed 's/chassis_id","float/chassis_id","string/g' | sed 's/all_chassis","float/all_chassis","string/g' | sed 's/_type","float/_type","string/g' |sed 's/VMType","float/VMType","string/g' | sed 's/Type","float/Type","string/g'  | sed 's/Name","float/Name","string/g' > /srv/customers/hotstorage/configs/$ver/$customer/$netelement_type/$csv_stripped.conf
	rm /srv/customers/hotstorage/configs/$ver/$customer/$netelement_type/$csv_stripped.conf1
	fi
done
